### ISSUE TITLE
Export fails in SVG w/ Animation

### ISSUE THREAD

**Issue by riskpeep** [martingraham/svgExport#2]
<repost from the Chrome extensions site since I'm not sure which one you monitor>

In svgexp.js, in parentChain around line 121.

elemData.class.split fails in some cases.

In my case, it was because elemData.class is of type SVGAnimatedString instead of type object.

I was able to fix locally by wrapping lines 121 - 132 with an if clause that checks the type of elemData.class like so:

function parentChain (elem, styles) {
    // Capture id / classes of svg's parent chain.
    var ownerDoc = elem.ownerDocument || document;
    var elemArr = [];
    while (elem.parentNode !== ownerDoc && elem.parentNode !== null) {
        elem = elem.parentNode;
        elemArr.push ({id: elem.id, class: elem.className});
    }

    // see if id or element class are referenced in any styles collected below the svg node
    // if not, null the id / class as they're not going to be relevant
    elemArr.forEach (function (elemData) {
        var presences = {id: false, class: false};
	if(typeof(elemData.class) == "string") {
	        var classes = elemData.class.split(" ").filter(function(a) { return a.length > 0; });   // v1.13: may be multiple classes in a containing class attribute
	        styles.forEach (function (style) {
	            for (var c = 0; c < classes.length; c++) {
	                if (style.indexOf ("."+classes[c]) >= 0) {
	                    presences.class = true;
	                    break;  // no need to keep looking through rest of classtypes if one is needed
	                }
	            }
	            if (elemData.id && style.indexOf ("#"+elemData.id) >= 0) {
	                presences.id = true;
        	    }
	        });
	};
        Object.keys(presences).forEach (function (presence) {
            if (!presences[presence]) { elemData[presence] = undefined; }
        });
    });

    return elemArr;
}

This fix is probably sub-optimal because it would miss styles on the elements causing the error. I figure you will know a better way.

With thanks,
Rob

**Comment by martingraham** [comment]
Thanks, I've had a look and I can rescue it a bit earlier in the code by setting class to be elem.getAttribute("class") which pulls out a string value, rather than elem.className which can return a svganimatedstring
